In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Urban_Park_Ranger_Animal_Condition_Response_Manhattan.csv')
#data.e = pd.write_csv('Urban_Park_Ranger_Animal_Condition_Response.csv')

In [4]:
data.head()

Date and Time of initial call Date and time of Ranger response    Borough  \
0                  5/9/19 11:30                     5/9/19 15:00  Manhattan   
1                 4/17/19 13:00                    4/17/19 13:30  Manhattan   
2                 5/22/19 14:00                    5/22/19 14:15  Manhattan   
3                 5/17/19 16:15                    5/17/19 16:15  Manhattan   
4                 5/14/19 15:54                    5/14/19 16:00  Manhattan   

              Property                                           Location  \
0         Central Park  Large Bald Cyprus on South East Corner of Harl...   
1         Central Park              Near Boathouse Restaurant Parking Lot   
2         Central Park                               5th Ave and 108th St   
3  Madison Square Park                                                NaN   
4         Central Park                              72nd St/ 5th ave wall   

  Species Description Call Source Species Status Animal Condition  \
0  American Goldfinch      Public         Native              DOA   
1      American Robin     Central         Native          Injured   
2      American Robin      Public         Native          Healthy   
3                 Bat    Employee         Native              NaN   
4                 Bat      Public         Native              NaN   

   Duration of Response  ...    311SR Number            Final Ranger Action  \
0                   0.5  ...             NaN  Relocated/Condition Corrected   
1                   1.0  ...  1-1-1706102711                  Rehabilitator   
2                   0.5  ...             NaN  Relocated/Condition Corrected   
3                   0.2  ...             NaN        Advised/Educated others   
4                   0.5  ...             NaN  Relocated/Condition Corrected   

  # of Animals PEP Response  Animal Monitored   Rehabilitator  \
0          1.0        False             False             NaN   
1          1.0        False             False  Wild Bird Fund   
2          1.0        False             False             NaN   
3          1.0         True             False             NaN   
4          1.0        False             False             NaN   

  Hours spent monitoring Police Response  ESU Response ACC Intake Number  
0                    NaN           False         False               NaN  
1                    NaN           False         False               NaN  
2                    NaN           False         False               NaN  
3                    NaN           False         False               NaN  
4                    NaN           False         False               NaN  

[5 rows x 22 columns]

In [5]:
data.shape

(475, 22)

In [6]:
data['Property'].unique()

array(['Central Park', 'Madison Square Park', 'Mercer Playground',
       'Inwood Hill Park', 'Highbridge Recreation Center',
       'Morningside park', 'Morningside Park', 'West Harlem Piers',
       'Hudson Park', 'Hudson River Park', 'Riverside Park',
       'Stuyvesant Square', 'Hester St. Playground', 'Bryant Park',
       'St. Nicholas Park', 'Thomas Jefferson Recreation Center',
       'Battery Park City', 'John V. Lindsay East River Park',
       'Fort Tryon Park', 'Sherman Creek', "Randall's Island Park",
       'Churchill School', 'Washington Market Park',
       'Fort Washington Park', 'Sutton Place Park', 'Central  Park',
       'Isham Park', 'Sheltering Arms Playground', 'James Finley Walk',
       'Carl Schurz Park', 'Jacob H. Schiff Playground',
       'Theodore Roosevelt Park', 'Abingdon Square',
       'Playground 103 CIII', 'J. Hood Wright Park',
       'Washington Square Park', 'Tompkins Square Park',
       'Robert Bendheim Playground', 'Mannahatta Park',
       'Be

In [7]:
number_of_properties = data['Property'].nunique()
print("There are "+str(number_of_properties)+" properties where wildlife have been spotted and the identifier"+
      " called the police")

There are 51 properties where wildlife have been spotted and the identifier called the police


In [8]:
number_of_species = data['Species Description'].nunique()

In [9]:
data['Species Description'].nunique()
print("There are "+str(number_of_species)+" types of wildlife that have been spotted and the identifier"+
      " called the police")

There are 62 types of wildlife that have been spotted and the identifier called the police


In [10]:
data.head()

Date and Time of initial call Date and time of Ranger response    Borough  \
0                  5/9/19 11:30                     5/9/19 15:00  Manhattan   
1                 4/17/19 13:00                    4/17/19 13:30  Manhattan   
2                 5/22/19 14:00                    5/22/19 14:15  Manhattan   
3                 5/17/19 16:15                    5/17/19 16:15  Manhattan   
4                 5/14/19 15:54                    5/14/19 16:00  Manhattan   

              Property                                           Location  \
0         Central Park  Large Bald Cyprus on South East Corner of Harl...   
1         Central Park              Near Boathouse Restaurant Parking Lot   
2         Central Park                               5th Ave and 108th St   
3  Madison Square Park                                                NaN   
4         Central Park                              72nd St/ 5th ave wall   

  Species Description Call Source Species Status Animal Condition  \
0  American Goldfinch      Public         Native              DOA   
1      American Robin     Central         Native          Injured   
2      American Robin      Public         Native          Healthy   
3                 Bat    Employee         Native              NaN   
4                 Bat      Public         Native              NaN   

   Duration of Response  ...    311SR Number            Final Ranger Action  \
0                   0.5  ...             NaN  Relocated/Condition Corrected   
1                   1.0  ...  1-1-1706102711                  Rehabilitator   
2                   0.5  ...             NaN  Relocated/Condition Corrected   
3                   0.2  ...             NaN        Advised/Educated others   
4                   0.5  ...             NaN  Relocated/Condition Corrected   

  # of Animals PEP Response  Animal Monitored   Rehabilitator  \
0          1.0        False             False             NaN   
1          1.0        False             False  Wild Bird Fund   
2          1.0        False             False             NaN   
3          1.0         True             False             NaN   
4          1.0        False             False             NaN   

  Hours spent monitoring Police Response  ESU Response ACC Intake Number  
0                    NaN           False         False               NaN  
1                    NaN           False         False               NaN  
2                    NaN           False         False               NaN  
3                    NaN           False         False               NaN  
4                    NaN           False         False               NaN  

[5 rows x 22 columns]

In [11]:
data['Location'].unique()

array(['Large Bald Cyprus on South East Corner of Harlem Meer, close to 106th St and 5th Ave',
       'Near Boathouse Restaurant Parking Lot', '5th Ave and 108th St',
       nan, '72nd St/ 5th ave wall',
       'near 100th St Pool, closer to 104th street, on rock outcrop',
       'Mercer st & Bleeker st',
       'Gaelic field, southeastern corner closer to the Marsh side, at the base of a London Plane tree GPS (40.873125, -73.921672)',
       '311 caller did not leave detailed location', '113th near steps',
       '125 street and West Harlem Piers Park', 'Pier 51',
       '12th street and West Street', 'Harlem Meer 40.796582, -73.950043',
       'Harlem Meer', "Linda's Lawn", 'The caves', 'Dykman Ball Fields',
       'M & O HQ District 12', "Dana Center Men's Restroom",
       'Dyckman Street and Staff Street',
       '151 St and Riverside PK by the bridge area',
       'Near the dog run at Isham Avenue and Seaman Street',
       '2nd ave and E15th street', 'Conservatory Waters',
     

In [12]:
data['Location'].nunique()

424

In [13]:
data['Species Status'].unique()

array(['Native', 'Exotic', 'Domestic', nan, 'Invasive'], dtype=object)

In [14]:
data['Call Source'].unique()

array(['Public', 'Central', 'Employee',
       'Conservancies/"Friends of" Groups', 'Other', 'Observed by Ranger'],
      dtype=object)

In [25]:
data['Animal Condition'].value_counts()

Unhealthy    187
Healthy       81
DOA           51
Injured       36
Name: Animal Condition, dtype: int64

In [26]:
data['Final Ranger Action'].value_counts()

ACC                              188
Unfounded                        107
Relocated/Condition Corrected     64
Monitored Animal                  47
Rehabilitator                     31
Advised/Educated others           29
Submitted for DEC Testing          9
Name: Final Ranger Action, dtype: int64

In [18]:
data['PEP Response'].unique()

array([False, True, nan], dtype=object)

In [19]:
data['Rehabilitator'].unique()

array([nan, 'Wild Bird Fund', 'Wild Bird Fund, Manhattan',
       'Wild Bird Fund Manhattan', 'WBF', 'Bobby Horvath',
       'Wildbird Fund', 'Animal Medical Center Manhattan', 'WINOR',
       'Animal Medical Center'], dtype=object)

In [24]:
data['Police Response'].value_counts()

False    461
True      12
Name: Police Response, dtype: int64

In [21]:
data['ESU Response'].unique()

array([False,  True])

In [22]:
data['ACC Intake Number'].unique()

array([nan, '40180/40181/40182', '46961', '48438', '51926', '39503',
       '54198', '38182', '37960', '37961', '37962', '38398', '37963',
       '53674', '56886', '64890', '55993', '60355', '55405', '60330',
       '50469', '37171', '39582', '36328', '37022', '39704', '39793',
       '39840', '54451', '59915', '37704', '31565', '34935', '35069',
       '35372', '35529', '35650', '35692', '35796', '35899', '36012',
       '36013', '36023', '36209', '36569', '36572', '36670', '36669',
       '36723', '36786', '36918', '37018', '37021', '37364', '37377',
       '37395', '37471', '37522', '37618', '37609', '37611', '37610',
       '37653', '37702', '37743', '38024', '38145', '38142', '38337',
       '38336', '38388', '38474', '38473', '38513', '38616', '38767',
       '38879', '38875', '38926', '38927', '39000', '39050',
       '1-1-1607314261', '39257; 39258', '39304', '39530, 39531', '40061',
       '40498', '40849', '50827', '52786', '43195', '36370', '37703',
       '38356', '35291', 

In [23]:
data.head()

Date and Time of initial call Date and time of Ranger response    Borough  \
0                  5/9/19 11:30                     5/9/19 15:00  Manhattan   
1                 4/17/19 13:00                    4/17/19 13:30  Manhattan   
2                 5/22/19 14:00                    5/22/19 14:15  Manhattan   
3                 5/17/19 16:15                    5/17/19 16:15  Manhattan   
4                 5/14/19 15:54                    5/14/19 16:00  Manhattan   

              Property                                           Location  \
0         Central Park  Large Bald Cyprus on South East Corner of Harl...   
1         Central Park              Near Boathouse Restaurant Parking Lot   
2         Central Park                               5th Ave and 108th St   
3  Madison Square Park                                                NaN   
4         Central Park                              72nd St/ 5th ave wall   

  Species Description Call Source Species Status Animal Condition  \
0  American Goldfinch      Public         Native              DOA   
1      American Robin     Central         Native          Injured   
2      American Robin      Public         Native          Healthy   
3                 Bat    Employee         Native              NaN   
4                 Bat      Public         Native              NaN   

   Duration of Response  ...    311SR Number            Final Ranger Action  \
0                   0.5  ...             NaN  Relocated/Condition Corrected   
1                   1.0  ...  1-1-1706102711                  Rehabilitator   
2                   0.5  ...             NaN  Relocated/Condition Corrected   
3                   0.2  ...             NaN        Advised/Educated others   
4                   0.5  ...             NaN  Relocated/Condition Corrected   

  # of Animals PEP Response  Animal Monitored   Rehabilitator  \
0          1.0        False             False             NaN   
1          1.0        False             False  Wild Bird Fund   
2          1.0        False             False             NaN   
3          1.0         True             False             NaN   
4          1.0        False             False             NaN   

  Hours spent monitoring Police Response  ESU Response ACC Intake Number  
0                    NaN           False         False               NaN  
1                    NaN           False         False               NaN  
2                    NaN           False         False               NaN  
3                    NaN           False         False               NaN  
4                    NaN           False         False               NaN  

[5 rows x 22 columns]